# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.1
  # Optionally, you can specify additional configurations here
  # For example, to disable certain cops or adjust their settings

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  # You can customize settings if needed

Style/StringLiterals:
  EnforcedStyle: double_quotes
