default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false

development:
  <<: *default
  database: SQUADMATCH_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: SQUADMATCH_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  # database: SQUADMATCH_production
  database: SQUADMATCH_development
  url: <%= ENV['DATABASE_URL'] %>
  # username: SQUADMATCH
  # password: <%= ENV["SQUADMATCH_DATABASE_PASSWORD"] %>
